version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./containers/api/Dockerfile
      target: pycharm
    volumes:
      - ./src:/src
    ports:
      - "8008:8000"
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64
    image: mysql:8.4
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./containers/mysql/db.env:/etc/mysql/conf.d/my2.cnf
    env_file:
      - ./containers/mysql/db.env
    ports:
      - "13316:3306"