"""test sql model add column

Revision ID: 3b21a9937bac
Revises: 78857baf9194
Create Date: 2024-10-08 16:55:49.546741

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b21a9937bac'
down_revision: Union[str, None] = '78857baf9194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_second', sa.Column('added_column', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_second', 'added_column')
    # ### end Alembic commands ###
