"""fix model define

Revision ID: 3eb76d80e112
Revises: 3b21a9937bac
Create Date: 2024-10-08 17:00:28.364537

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3eb76d80e112'
down_revision: Union[str, None] = '3b21a9937bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_second_description', table_name='items_second')
    op.drop_index('ix_items_second_title', table_name='items_second')
    op.drop_table('items_second')
    op.drop_index('ix_users_second_email', table_name='users_second')
    op.drop_table('users_second')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_second',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
                    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['users_second.id'], name='items_second_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_items_second_title', 'items_second', ['title'], unique=False)
    op.create_index('ix_items_second_description', 'items_second', ['description'], unique=False)
    op.create_table('users_second',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
                    sa.Column('hashed_password', mysql.VARCHAR(length=100), nullable=False),
                    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
                    sa.Column('added_column', mysql.VARCHAR(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_users_second_email', 'users_second', ['email'], unique=True)
    # ### end Alembic commands ###
