"""add cloumn to user table

Revision ID: 8b5d3a274c9c
Revises: 6688846d6eb7
Create Date: 2024-10-07 18:03:34.559955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5d3a274c9c'
down_revision: Union[str, None] = '6688846d6eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('added_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'added_column')
    # ### end Alembic commands ###
